version: '3'
services:
  app-name:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-name
    volumes:
      - .:/home/node/app
    cap_add:
      - SYS_ADMIN
    environment:
      - NODE_ENV=development
    working_dir: /home/node/app
    command: sls offline start
    ports:
      - "4000:4000"